training_attendance/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :trainings do
    resources :people
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

training_attendance/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

training_attendance/app/models/person.rb
class Person < ApplicationRecord
  belongs_to :training
end

training_attendance/app/models/training.rb
class Training < ApplicationRecord
  has_many :people
  validates :date, presence: true,
                   length: { minimum: 5 }
  validates :location, presence: true,
                    length: { minimum: 10 }
end

training_attendance/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

training_attendance/app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def create
    @training = Training.find(params[:training_id])
    @person = @training.people.create(person_params)
    redirect_to training_path(@training)
  end

private
  def person_params
    params.require(:person).permit(:name, :status)
  end

end

training_attendance/app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

def index
  @trainings = Training.all
end

def show
  @training = Training.find(params[:id])
end

def new
  @training = Training.new
end

def edit
  @training = Training.find(params[:id])
end

def create

    @training = Training.new(params.require(:training).permit(:date, :location))
    if @training.save
    redirect_to @training
    else render 'new'
    end
end

def update
  @training = Training.find(params[:id])

  if @training.update(training_params)
    redirect_to @training
  else
    render 'edit'
  end
end

def destroy
  @training = Training.find(params[:id])
  @training.destroy

  redirect_to trainings_path
end

private
  def training_params
    params.require(:training).permit(:date, :location)
  end
end

training_attendance/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

training_attendance/app/helpers/application_helper.rb
module ApplicationHelper
end

training_attendance/app/helpers/people_helper.rb
module PeopleHelper
end

training_attendance/app/helpers/trainings_helper.rb
module TrainingsHelper
end

training_attendance/app/helpers/welcome_helper.rb
module WelcomeHelper
end

training_attendance/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingAttendance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

training_attendance/app/views/trainings/edit.html.erb
<h1> Edit Training </h1>

<%= form_for(@training) do |f| %>

  <% if @training.errors.any? %>
    <div id="error_explanation">
    <h2>
      <%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:
      </h2>
      <ul>
      <% @training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :date_and_time %><br>
      <%= f.text_area :date %>
    </p>

    <p>
      <%= f.label :location %><br>
      <%= f.text_area :location %>
    </p>

    <p>
      <%= f.submit %>
    </p>

  <% end %>

  <%= link_to 'Back', trainings_path %>

training_attendance/app/views/trainings/index.html.erb
<h1> Listing Trainings </h1>
<%= link_to 'New Training', new_training_path %>

<table>
  <tr>
    <th>Date</th>
    <th>Location</th>
    <th>Count</th>
    <th colspan="2"></th>
  </tr>

  <% @trainings.each do |training| %>
    <tr>
      <td><%= training.date %></td>
      <td><%= training.location %></td>
      <td><%= training.people.where(status: "yes").count %></td>
      <td><%= link_to 'Show', training_path(training) %></td>
      <td><%= link_to 'Edit', edit_training_path(training) %></td>
      <td><%= link_to 'Destroy', training_path(training),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete this training?'} %></td>

    </tr>
  <% end %>
</table>

training_attendance/app/views/trainings/new.html.erb
<h1> New Training </h1>

<%= form_for :training, url: trainings_path do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@training.errors.count, "error") %> prohibited
        this training from being saved:
      </h2>
      <ul>
        <% @training.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= f.label :date_and_time %><br>
  <%= f.text_field :date %>
</p>

<p>
  <%= f.label :location %><br>
  <%= f.text_area :location %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>
<%= link_to 'Back', trainings_path %>

training_attendance/app/views/trainings/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @training.date %>
</p>

<p>
  <strong>Text:</strong>
  <%= @training.location %>
</p>

<h2> Attendees </h2>
<% @training.people.each do |person| %>
  <p>
    <strong>person:</strong>
    <%= person.name %>
  </p>

  <p>
    <strong>Status: </strong>
    <%= person.status %>
  </p>
<% end %>

<h2>Will you attend?</h2>
<%= form_for([@training, @training.people.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Yes %>
    <%= f.radio_button :status, "yes" %><br>
    <%= f.label :No %>
    <%= f.radio_button :status, "no" %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Destroy', training_path(@training),
        method: :delete,
        data: { confirm: 'Are you sure you want to delete this training?'} %></td> |
<%= link_to 'Back', trainings_path %>

training_attendance/app/views/welcome/index.html.erb
<h1>Hi, this is the start of my training attendance app</h1>
<%= link_to 'List of Trainings', controller: 'trainings' %>